# Generated by Django 3.1.14 on 2024-03-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('title_en', models.CharField(max_length=200, verbose_name='название на английском')),
                ('title_jp', models.CharField(max_length=200, verbose_name='название на японском')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='из кого эмолюционировал')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='появится в')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='исчез в')),
                ('level', models.IntegerField(blank=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='здоровье')),
                ('strength', models.IntegerField(blank=True, verbose_name='атака')),
                ('defence', models.IntegerField(blank=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='покемон')),
            ],
        ),
    ]
