# Generated by Django 3.1.14 on 2024-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20240330_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_description',
            field=models.TextField(null=True),
        ),
    ]
