# Generated by Django 3.1.14 on 2024-03-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20240330_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_description',
            new_name='description',
        ),
    ]
